export const USER_GET_CURRENT_SUCCESS = 'USER_GET_CURRENT_SUCCESS';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';


export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const SET_SIGNUP_STEP = 'SET_SIGNUP_STEP';
export const USER_SET_CATEGORY = 'USER_SET_CATEGORY';
export const USER_SET_SUBCATEGORY = 'USER_SET_SUBCATEGORY';
export const USER_SET_CUSTOMSUBCATEGORY = 'USER_SET_CUSTOMSUBCATEGORY';
export const USER_SET_TYPE = 'USER_SET_TYPE';
export const USER_SET_COUNTRY = 'USER_SET_COUNTRY';
export const USER_SET_CITY = 'USER_SET_CITY';
export const USER_SET_POSITION = 'USER_SET_POSITION';
export const USER_SET_STATE = 'USER_SET_STATE';
export const USER_SET_SCHOOL = 'USER_SET_SCHOOL';
export const USER_SET_FIRSTNAME = 'USER_SET_FIRSTNAME';
export const USER_SET_LASTNAME = 'USER_SET_LASTNAME';
export const USER_SET_EMAIL = 'USER_SET_EMAIL';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_SET_SEX = 'USER_SET_SEX';
export const USER_SET_BIRTDAY = 'USER_SET_BIRTDAY';
export const SET_SIGNUP_MULTIPLE_FIELDS = 'SET_SIGNUP_MULTIPLE_FIELDS';


export const LOG_OUT = 'LOG_OUT';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';
export const CHANGE_SETTINGS_FIELDS = 'CHANGE_SETTINGS_FIELDS';
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';

export const GET_FOUNDED_USERS = 'GET_FOUNDED_USERS';

export const SET_RELATIONS_AFTER_ADD = 'SET_RELATIONS_AFTER_ADD';
export const SET_RELATIONS_AFTER_REMOVE = 'SET_RELATIONS_AFTER_REMOVE';
export const SET_RELATIONS_AFTER_APPROVE = 'SET_RELATIONS_AFTER_APPROVE';


// friends
export const FRIENDS_GET_FRIENDS_SUCCESS = 'FRIENDS_GET_FRIENDS_SUCCESS';
export const FRIENDS_GET_SUGGESTED_SUCCESS = 'FRIENDS_GET_SUGGESTED_SUCCESS';
export const FRIENDS_GET_PENDING_SUCCESS = 'FRIENDS_GET_PENDING_SUCCESS';
export const FRIENDS_GET_REQUESTED_SUCCESS = 'FRIENDS_GET_REQUESTED_SUCCESS';

// end friends


//messages

export const MESSAGES_GET_FRIEND_MESSAGES = 'MESSAGES_GET_FRIEND_MESSAGES';
export const MESSAGES_SEND_MESSAGE = 'MESSAGES_SEND_MESSAGE';
export const MESSAGES_SET_ROOM = 'MESSAGES_SET_ROOM';
export const SET_CHAT_WITH = 'SET_CHAT_WITH';
export const MESSAGES_RECEIVE_MESSAGE = 'MESSAGES_RECEIVE_MESSAGE';
export const MESSAGES_SET_TEXT = 'MESSAGES_SET_TEXT';
export const MESSAGES_ADD_MESSAGE = 'MESSAGES_ADD_MESSAGE';
export const MESSAGES_SET_IN_ACTION = 'MESSAGES_SET_IN_ACTION';
export const START_SEND_MESSAGE = 'START_SEND_MESSAGE';
export const SUCCESS_SEND_MESSAGE = 'SUCCESS_SEND_MESSAGE';
export const FAIL_SEND_MESSAGE = 'FAIL_SEND_MESSAGE';
export const SET_BLOCKING_STATUS = 'SET_BLOCKING_STATUS';
export const SET_MESSAGE_SEEN = 'SET_MESSAGE_SEEN';
export const MESSAGES_SET_ROOMS = 'MESSAGES_SET_ROOMS';

// end messages

// posts

export const SUCCESS_GET_POSTS = 'SUCCESS_GET_POSTS';
export const SUCCESS_GET_NEWSFEED = 'SUCCESS_GET_NEWSFEED';
export const SET_POST_LIKE = 'SET_POST_LIKE';
export const SET_POST_UNLIKE = 'SET_POST_UNLIKE';
export const EDIT_POST = 'EDIT_POST';
export const SET_NEWSFEED = 'SET_NEWSFEED';
export const SET_POST = 'SET_NEWSFEED';
export const SET_POSTS_AND_NEWSFEED = 'SET_POSTS_AND_NEWSFEED';

// end posts





// Admin 
export const GET_LIST_OF_ANNOUNCEMENTS = 'GET_LIST_OF_ANNOUNCEMENTS';
export const SET_ANNOUNCEMENTS = 'SET_ANNOUNCEMENTS';
 // end of Admin