export const SUCCESS_GET_TASKS = 'SUCCESS_GET_TASKS';
export const SUCCESS_CREATE_TASK = 'SUCCESS_CREATE_TASK';
export const SUCCESS_EDIT_TASK = 'SUCCESS_EDIT_TASK';
export const LOGIN_TO_ADMIN = 'LOGIN_TO_ADMIN';
export const SET_QUERY = 'SET_QUERY';
